### ISSUE TITLE
Calling CoinigWsClient() throws "System.Missing.MethodException"

### ISSUE THREAD

**Issue by matthiasguentert** [coinigy/WebsocketAPIClient#3] opened 2018-03-17 21:24 UTC
Unfortunately, when calling the ctor it complains with: 

> System.MissingMethodException
>   HResult=0x80131513
>   Message=Methode nicht gefunden: "Void PureSocketCluster.PureSocketClusterSocket..ctor(System.String, System.Tuple`2<System.String,System.String>, Int32)".
>   Source=CoinigyWebsocketClient
>   StackTrace:
>    at CoinigyWebsocketClient.CoinigyWsClient..ctor(IApiCredentials credentials, Boolean debug, String url)
>    at ConsoleApp1.Program.Main(String[] args) in ...

I am working with VS2017, target framework is .NET Framework 4.6.1. I have installed the Class Library via NuGet package manager. What am I doing wrong here?

**Comment by ByronAP** [comment] 2018-03-18 02:48
Not sure, I will get back to you ASAP, might be some kind of break in the libraries that I missed

**Comment by matthiasguentert** [comment] 2018-03-18 08:11
Thanks for the quick reply. I think I may have found the culprit, although not sure... 

The constructors signatures seems to have changed in PureSocketCluster class library betweend version 1.1.1 and 2.0.1. The latest version (2.0.1) gets pulled in when installing WebsocketAPIClient via NuGet. 

Version 1.1.1 is getting used by CoinigyWebsocket**Demo** which works just fine. 

So I went back to the NuGet Package Manager and switched the version of PureSocketCluster to version 1.1.1. Unfortunately the same exception occurs when calling the ctor...

**Comment by Guidera** [comment] 2018-03-21 00:04
Hi Byron,

I am trying to subscribe to multiple channels using your websocket implementation. The output works but the problem is that it seems to retrieve information only from the first channel for the subscribed list, which is BINANCE and get stuck is this exchange. I suppose I did something wrong and that the method client_OnOrderMessage() should retrieve information for all channels subscribed, right?

Would this be anything related to any restriction limits in the API free accounts or would that be an error I did?

below the code:

`private static void Client_OnClientReady()
        {
            channels = _client.GetChannels();
            foreach (var channel in channels)
            {
                if (channel.ToString().Contains("ORDER"))
                {
                    OutputConsole.WriteLine(channel.ToString(), ConsoleColor.Cyan);
                    _client.SubscribeToChannel(channel.ToString());
                }       
.....
...
..        
          }}`

**Comment by ByronAP** [comment] 2018-03-22 15:16
sorry for the delay I am working on this right now

**Comment by ByronAP** [comment] 2018-03-22 15:22
ok I need to update this package to be able to make use of the latest ref packages because it increase performance the json package has been changed to Utf8Json

**Comment by ByronAP** [comment] 2018-05-05 02:44
yep I am way late getting to this but expect a new library

**Comment by ByronAP** [comment] 2018-05-06 20:46
closing with v2.0.0 release

**Closed as completed by ByronAP** 2018-05-06 20:46 UTC
